### ISSUE TITLE
It seems that this project lost head file "gtest.h" cause I can't compile OK.

### ISSUE THREAD

**Issue by zxdCodeLibrary** [ez8-co/linked_hash#1]
My ide is VS2015，and I  use cmake tool convert this project to windows style.
This step is OK.
Such as following:
E:\cmake_source\linked_hash-master\test> cmake . -G "Visual Studio 14 2015"
-- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.0.23506.0
-- The CXX compiler identification is MSVC 19.0.23506.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: E:/cmake_source/linked_hash-master/test

But when I use nmake command,it failed,cause' 'gtest.h' file lost.

Can you provide this file on your project?

**Comment by orca-zhang** [comment]
FYR:

https://github.com/google/googletest

**Comment by zxdCodeLibrary** [comment]
I tried to test your linked hash map functions and compared it with std::map,std::unorderd_map.Your wrapped map did show a much better performance on my test projects.In future I would like to use it and try to improve my server performance,thanks a lot for your contribution!

**Comment by orca-zhang** [comment]
Thanks a lot for your appreciation.
There're many tricky ways you can find in `linked_hash`.

: )
